name: Streamlit App Deployment

on:
  push:
    branches:
      - 2024-25

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt
        pip install distutils

    - name: Run Streamlit
      run: |
        streamlit run strmlit_app.py
